services:
  go-app:
    container_name: go-app
    build: .
    # env_file:
      # - .env
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=users_db sslmode=disable"
    depends_on:
      - go_db
  go_db:
    image: postgres:alpine
    restart: always
    ports:
      - "2345:5432"
    container_name: go_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_db
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./data:/docker/entry-point-initdb.d
# volumes:
#   db_data: {}
